# site.yml
---
- hosts: Proj15LAMP
  vars:
    dbname: naamTest
    dbuser: userTest
    dbpasswd: passTest
  sudo: true
  roles:
    - common
    - web
    - db
    - update
    - miscLamp
    
- hosts: Proj15JEE
  sudo: true
  vars:
    tomcat_enabled: true
    tomcat_server_port: 8080
    tomcat_catalina_port: 8983
    tomcat_catalina_redirect_port: 8443
    tomcat_hostname: localhost
  roles:
    - common
    - java
    - tomcat
    - update
