---
# file java/tasks/main.yml
- name: Install tomcat
  yum: pkg={{item}} state=latest
  with_items:
    - tomcat
    - tomcat-webapps
    - tomcat-admin-webapps
    
- name: Download tomcat-tools
  command: "cd /tmp/"
  command: "wget http://apache.cu.be/tomcat/tomcat-7/v7.0.59/bin/apache-tomcat-7.0.59.tar.gz"
  command: "tar xzf apache-tomcat-7.0.59.tar.gz"
  command: "sudo mv apache-tomcat-7.0.59 /usr/local/tomcat7"

- name: Tomcat autostarten
  command: "sudo echo 'bash /usr/local/tomcat7/bin/startup.sh' > /etc/init.d/startTomcat"
  command: "sudo chmod +x /etc/init.d/startTomcat"
